### ISSUE TITLE
OpenVPN monitoring

### ISSUE THREAD

**Issue by PrzemekSkw** [EnKrypt/Doppler#20]
Hi, Thank You very much for that project. I use Doppler for monitor my VPS debian server where I have openvpn server installed and I'm missing feauture to monitor my vpn connections. Is it possible to add openvpn to Doppler?

Regards.

**Comment by EnKrypt** [comment]
It might be possible, but I don't know if it aligns with the goals for a product that is meant to be zero configuration.

A feature like this will either require configuration or it will be a dead feature for all the other users who do not run OpenVPN.

So I guess the answer is yes, it is possible, and you are welcome to fork this project and build that feature and I might be able to provide assistance; but unfortunately I don't think it can be built into the current version of Doppler as it stands.

Hope that answers your question, and thanks for checking Doppler out!
